server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://172.17.180.145:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mybatis-mapper/com/**/mapper/*.xml
