server:
  port: 8081

minio:
  endpoint: 192.168.101.130
  port: 9000
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  secure: false
  bucketName: "test"
  configDir: "/data"
