server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://172.17.180.145:3306/visual?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.lqz.demo.mapper: debug