server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.71.129:3306/max_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver